export const catalogPlaceholder = {
  catalogs: [
    {
      id: 'catalog',
      description: 'Root catalog',
      stac_version: '1.0.0',
      links: [
        {
          rel: 'aggregate',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/catalogs/convert-stac/catalogs/catalog/aggregate',
        },
        {
          rel: 'aggregations',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/catalogs/convert-stac/catalogs/catalog/aggregations',
        },
        {
          rel: 'catalogs',
          type: 'application/geo+json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/catalogs/convert-stac/catalogs/catalog/catalogs',
        },
        {
          rel: 'collections',
          type: 'application/geo+json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/catalogs/convert-stac/catalogs/catalog/collections',
        },
        {
          rel: 'conformance',
          type: 'application/json',
          title: 'STAC/WFS3 conformance classes implemented by this server',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/conformance',
        },
        {
          rel: 'data',
          type: 'application/geo+json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/catalogs/convert-stac/catalogs/catalog/collections',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/catalogs/convert-stac/catalogs/catalog/search',
          method: 'GET',
        },
        {
          rel: 'parent',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/catalogs/convert-stac',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/catalogs/convert-stac/catalogs/catalog/search',
          method: 'POST',
        },
        {
          rel: 'queryables',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/catalogs/convert-stac/catalogs/catalog/queryables',
        },
        {
          rel: 'root',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/',
        },
        {
          rel: 'self',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/catalogs/convert-stac/catalogs/catalog',
        },
        {
          rel: 'child',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/catalogs/convert-stac/catalogs/catalog/collections/col_5ac44528-1ab2-11f0-a9f8-b629de958b72',
          title: 'Result Collection for Job 5ac44528-1ab2-11f0-a9f8-b629de958b72',
        },
        {
          rel: 'child',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/catalogs/convert-stac/catalogs/catalog/collections/col_5c5cbd0c-1ab2-11f0-9c9f-b629de958b72',
          title: 'Result Collection for Job 5c5cbd0c-1ab2-11f0-9c9f-b629de958b72',
        },
        {
          rel: 'child',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/catalogs/convert-stac/catalogs/catalog/collections/col_5d358cea-1ab2-11f0-83fa-b629de958b72',
          title: 'Result Collection for Job 5d358cea-1ab2-11f0-83fa-b629de958b72',
        },
        {
          rel: 'child',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/catalogs/convert-stac/catalogs/catalog/collections/col_5e2cec38-1ab2-11f0-bf43-b629de958b72',
          title: 'Result Collection for Job 5e2cec38-1ab2-11f0-bf43-b629de958b72',
        },
      ],
      type: 'Catalog',
      stac_extensions: [],
      title: '',
      conformsTo: [
        'https://api.stacspec.org/v1.0.0/item-search#sort',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-json',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30',
        'https://api.stacspec.org/v1.0.0-rc.1/item-search#free-text',
        'https://api.stacspec.org/v1.0.0-rc.2/item-search#filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/basic-cql2',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-text',
        'https://api.stacspec.org/v1.0.0/item-search#fields',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search#free-text',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/filter',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search',
        'http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/simple-query',
        'https://api.stacspec.org/v1.0.0/collections',
        'http://www.opengis.net/spec/cql2/1.0/conf/advanced-comparison-operators',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core',
        'https://api.stacspec.org/v1.0.0/item-search',
        'https://api.stacspec.org/v1.0.0/item-search#query',
        'https://api.stacspec.org/v0.3.0/aggregation',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/features-filter',
        'https://api.stacspec.org/v1.0.0-rc.1/ogcapi-features#free-text',
        'https://api.stacspec.org/v1.0.0/core',
        'https://api.stacspec.org/v1.0.0/ogcapi-features',
      ],
    },
    {
      id: 'commercial-data',
      description: 'Catalog for dev-test-workspace commercial data',
      stac_version: '1.0.0',
      links: [
        {
          rel: 'aggregate',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/commercial-data/aggregate',
        },
        {
          rel: 'aggregations',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/commercial-data/aggregations',
        },
        {
          rel: 'catalogs',
          type: 'application/geo+json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/commercial-data/catalogs',
        },
        {
          rel: 'collections',
          type: 'application/geo+json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/commercial-data/collections',
        },
        {
          rel: 'conformance',
          type: 'application/json',
          title: 'STAC/WFS3 conformance classes implemented by this server',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/conformance',
        },
        {
          rel: 'data',
          type: 'application/geo+json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/commercial-data/collections',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/commercial-data/search',
          method: 'GET',
        },
        {
          rel: 'parent',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/commercial-data/search',
          method: 'POST',
        },
        {
          rel: 'queryables',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/commercial-data/queryables',
        },
        {
          rel: 'root',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/',
        },
        {
          rel: 'self',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/commercial-data',
        },
        {
          rel: 'child',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/commercial-data/collections/test-dev-collection-4',
          title: 'test-dev-collection-4',
        },
        {
          rel: 'child',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/commercial-data/collections/test-dev-collection-5',
          title: 'test-dev-collection-5',
        },
        {
          rel: 'child',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/commercial-data/collections/test-dev-collection-6',
          title: 'test-dev-collection-6',
        },
      ],
      title: 'dev-test-workspace Commercial Data',
      type: 'Catalog',
      stac_extensions: [],
      conformsTo: [
        'https://api.stacspec.org/v1.0.0/item-search#sort',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-json',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30',
        'https://api.stacspec.org/v1.0.0-rc.1/item-search#free-text',
        'https://api.stacspec.org/v1.0.0-rc.2/item-search#filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/basic-cql2',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-text',
        'https://api.stacspec.org/v1.0.0/item-search#fields',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search#free-text',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/filter',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search',
        'http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/simple-query',
        'https://api.stacspec.org/v1.0.0/collections',
        'http://www.opengis.net/spec/cql2/1.0/conf/advanced-comparison-operators',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core',
        'https://api.stacspec.org/v1.0.0/item-search',
        'https://api.stacspec.org/v1.0.0/item-search#query',
        'https://api.stacspec.org/v0.3.0/aggregation',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/features-filter',
        'https://api.stacspec.org/v1.0.0-rc.1/ogcapi-features#free-text',
        'https://api.stacspec.org/v1.0.0/core',
        'https://api.stacspec.org/v1.0.0/ogcapi-features',
      ],
    },
    {
      id: 'convert-stac',
      description: 'Catalog for storing data generated by workflow convert-stac',
      stac_version: '1.0.0',
      links: [
        {
          rel: 'aggregate',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/catalogs/convert-stac/aggregate',
        },
        {
          rel: 'aggregations',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/catalogs/convert-stac/aggregations',
        },
        {
          rel: 'catalogs',
          type: 'application/geo+json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/catalogs/convert-stac/catalogs',
        },
        {
          rel: 'collections',
          type: 'application/geo+json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/catalogs/convert-stac/collections',
        },
        {
          rel: 'conformance',
          type: 'application/json',
          title: 'STAC/WFS3 conformance classes implemented by this server',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/conformance',
        },
        {
          rel: 'data',
          type: 'application/geo+json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/catalogs/convert-stac/collections',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/catalogs/convert-stac/search',
          method: 'GET',
        },
        {
          rel: 'parent',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/catalogs/convert-stac/search',
          method: 'POST',
        },
        {
          rel: 'queryables',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/catalogs/convert-stac/queryables',
        },
        {
          rel: 'root',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/',
        },
        {
          rel: 'self',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/catalogs/convert-stac',
        },
        {
          rel: 'child',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/catalogs/convert-stac/catalogs/catalog',
          title: 'catalog',
        },
      ],
      title: 'convert-stac Outputs Catalog',
      type: 'Catalog',
      stac_extensions: [],
      conformsTo: [
        'https://api.stacspec.org/v1.0.0/item-search#sort',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-json',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30',
        'https://api.stacspec.org/v1.0.0-rc.1/item-search#free-text',
        'https://api.stacspec.org/v1.0.0-rc.2/item-search#filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/basic-cql2',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-text',
        'https://api.stacspec.org/v1.0.0/item-search#fields',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search#free-text',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/filter',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search',
        'http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/simple-query',
        'https://api.stacspec.org/v1.0.0/collections',
        'http://www.opengis.net/spec/cql2/1.0/conf/advanced-comparison-operators',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core',
        'https://api.stacspec.org/v1.0.0/item-search',
        'https://api.stacspec.org/v1.0.0/item-search#query',
        'https://api.stacspec.org/v0.3.0/aggregation',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/features-filter',
        'https://api.stacspec.org/v1.0.0-rc.1/ogcapi-features#free-text',
        'https://api.stacspec.org/v1.0.0/core',
        'https://api.stacspec.org/v1.0.0/ogcapi-features',
      ],
    },
    {
      id: 'processing-results',
      description: 'Catalog for dev-test-workspace processing results',
      stac_version: '1.0.0',
      links: [
        {
          rel: 'aggregate',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/aggregate',
        },
        {
          rel: 'aggregations',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/aggregations',
        },
        {
          rel: 'catalogs',
          type: 'application/geo+json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/catalogs',
        },
        {
          rel: 'collections',
          type: 'application/geo+json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/collections',
        },
        {
          rel: 'conformance',
          type: 'application/json',
          title: 'STAC/WFS3 conformance classes implemented by this server',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/conformance',
        },
        {
          rel: 'data',
          type: 'application/geo+json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/collections',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/search',
          method: 'GET',
        },
        {
          rel: 'parent',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/search',
          method: 'POST',
        },
        {
          rel: 'queryables',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/queryables',
        },
        {
          rel: 'root',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/',
        },
        {
          rel: 'self',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results',
        },
        {
          rel: 'child',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/processing-results/catalogs/convert-stac',
          title: 'convert-stac Outputs Catalog',
        },
      ],
      title: 'dev-test-workspace Processing Results',
      type: 'Catalog',
      stac_extensions: [],
      conformsTo: [
        'https://api.stacspec.org/v1.0.0/item-search#sort',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-json',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30',
        'https://api.stacspec.org/v1.0.0-rc.1/item-search#free-text',
        'https://api.stacspec.org/v1.0.0-rc.2/item-search#filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/basic-cql2',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-text',
        'https://api.stacspec.org/v1.0.0/item-search#fields',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search#free-text',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/filter',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search',
        'http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/simple-query',
        'https://api.stacspec.org/v1.0.0/collections',
        'http://www.opengis.net/spec/cql2/1.0/conf/advanced-comparison-operators',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core',
        'https://api.stacspec.org/v1.0.0/item-search',
        'https://api.stacspec.org/v1.0.0/item-search#query',
        'https://api.stacspec.org/v0.3.0/aggregation',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/features-filter',
        'https://api.stacspec.org/v1.0.0-rc.1/ogcapi-features#free-text',
        'https://api.stacspec.org/v1.0.0/core',
        'https://api.stacspec.org/v1.0.0/ogcapi-features',
      ],
    },
    {
      id: 'saved-data',
      description: 'Catalog for dev-test-workspace saved data',
      stac_version: '1.0.0',
      links: [
        {
          rel: 'aggregate',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/saved-data/aggregate',
        },
        {
          rel: 'aggregations',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/saved-data/aggregations',
        },
        {
          rel: 'catalogs',
          type: 'application/geo+json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/saved-data/catalogs',
        },
        {
          rel: 'collections',
          type: 'application/geo+json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/saved-data/collections',
        },
        {
          rel: 'conformance',
          type: 'application/json',
          title: 'STAC/WFS3 conformance classes implemented by this server',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/conformance',
        },
        {
          rel: 'data',
          type: 'application/geo+json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/saved-data/collections',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/saved-data/search',
          method: 'GET',
        },
        {
          rel: 'parent',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/saved-data/search',
          method: 'POST',
        },
        {
          rel: 'queryables',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/saved-data/queryables',
        },
        {
          rel: 'root',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/',
        },
        {
          rel: 'self',
          type: 'application/json',
          href: 'https://dev.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/dev-test-workspace/catalogs/saved-data',
        },
      ],
      title: 'dev-test-workspace Saved Data',
      type: 'Catalog',
      stac_extensions: [],
      conformsTo: [
        'https://api.stacspec.org/v1.0.0/item-search#sort',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-json',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30',
        'https://api.stacspec.org/v1.0.0-rc.1/item-search#free-text',
        'https://api.stacspec.org/v1.0.0-rc.2/item-search#filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/basic-cql2',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-text',
        'https://api.stacspec.org/v1.0.0/item-search#fields',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search#free-text',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/filter',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search',
        'http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/simple-query',
        'https://api.stacspec.org/v1.0.0/collections',
        'http://www.opengis.net/spec/cql2/1.0/conf/advanced-comparison-operators',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core',
        'https://api.stacspec.org/v1.0.0/item-search',
        'https://api.stacspec.org/v1.0.0/item-search#query',
        'https://api.stacspec.org/v0.3.0/aggregation',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/features-filter',
        'https://api.stacspec.org/v1.0.0-rc.1/ogcapi-features#free-text',
        'https://api.stacspec.org/v1.0.0/core',
        'https://api.stacspec.org/v1.0.0/ogcapi-features',
      ],
    },
  ],
  numReturned: 10,
  numMatched: 19,
};
