export const catalogPlaceholder = {
  catalogs: [
    {
      id: 'airbus_phr_qa',
      description: 'Root catalog for airbus_phr QA checks',
      stac_version: '1.0.0',
      links: [
        {
          rel: 'aggregate',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/catalogs/qa-workflow/catalogs/airbus_phr_qa/aggregate',
        },
        {
          rel: 'aggregations',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/catalogs/qa-workflow/catalogs/airbus_phr_qa/aggregations',
        },
        {
          rel: 'catalogs',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/catalogs/qa-workflow/catalogs/airbus_phr_qa/catalogs',
        },
        {
          rel: 'collections',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/catalogs/qa-workflow/catalogs/airbus_phr_qa/collections',
        },
        {
          rel: 'conformance',
          type: 'application/json',
          title: 'STAC/WFS3 conformance classes implemented by this server',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/conformance',
        },
        {
          rel: 'data',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/catalogs/qa-workflow/catalogs/airbus_phr_qa/collections',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/catalogs/qa-workflow/catalogs/airbus_phr_qa/search',
          method: 'GET',
        },
        {
          rel: 'parent',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/catalogs/qa-workflow',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/catalogs/qa-workflow/catalogs/airbus_phr_qa/search',
          method: 'POST',
        },
        {
          rel: 'queryables',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/catalogs/qa-workflow/catalogs/airbus_phr_qa/queryables',
        },
        {
          rel: 'root',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/',
        },
        {
          rel: 'self',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/catalogs/qa-workflow/catalogs/airbus_phr_qa',
        },
        {
          rel: 'child',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/catalogs/qa-workflow/catalogs/airbus_phr_qa/collections/qa_documentation',
          title: 'qa_documentation',
        },
        {
          rel: 'child',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/catalogs/qa-workflow/catalogs/airbus_phr_qa/collections/qa_radiometric',
          title: 'qa_radiometric',
        },
      ],
      type: 'Catalog',
      stac_extensions: [],
      title: '',
      conformsTo: [
        'https://api.stacspec.org/v1.0.0/item-search',
        'http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/simple-query',
        'https://api.stacspec.org/v1.0.0/item-search#query',
        'https://api.stacspec.org/v1.0.0-rc.2/item-search#filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-text',
        'https://api.stacspec.org/v1.0.0/ogcapi-features',
        'https://api.stacspec.org/v1.0.0/collections',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson',
        'https://api.stacspec.org/v1.0.0-rc.1/ogcapi-features#free-text',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search#free-text',
        'https://api.stacspec.org/v1.0.0/core',
        'https://api.stacspec.org/v1.0.0-rc.1/item-search#free-text',
        'https://api.stacspec.org/v1.0.0/item-search#fields',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/basic-cql2',
        'https://api.stacspec.org/v1.0.0/item-search#sort',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/features-filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-json',
        'http://www.opengis.net/spec/cql2/1.0/conf/advanced-comparison-operators',
        'https://api.stacspec.org/v0.3.0/aggregation',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search',
      ],
    },
    {
      id: 'cat_0721004e-fe8a-11ef-a4fd-925b27b1cd31',
      description:
        'This catalog contains monthly Land Surface Temperature (LST) collections derived from SLSTR sensors on Sentinel-3A and Sentinel-3B satellites. Data are split into daytime and nighttime observations, composited at a 0.01-degree resolution.',
      stac_version: '1.0.0',
      links: [
        {
          rel: 'aggregate',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/catalogs/cat_0721004e-fe8a-11ef-a4fd-925b27b1cd31/aggregate',
        },
        {
          rel: 'aggregations',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/catalogs/cat_0721004e-fe8a-11ef-a4fd-925b27b1cd31/aggregations',
        },
        {
          rel: 'catalogs',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/catalogs/cat_0721004e-fe8a-11ef-a4fd-925b27b1cd31/catalogs',
        },
        {
          rel: 'collections',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/catalogs/cat_0721004e-fe8a-11ef-a4fd-925b27b1cd31/collections',
        },
        {
          rel: 'conformance',
          type: 'application/json',
          title: 'STAC/WFS3 conformance classes implemented by this server',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/conformance',
        },
        {
          rel: 'data',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/catalogs/cat_0721004e-fe8a-11ef-a4fd-925b27b1cd31/collections',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/catalogs/cat_0721004e-fe8a-11ef-a4fd-925b27b1cd31/search',
          method: 'GET',
        },
        {
          rel: 'parent',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/catalogs/cat_0721004e-fe8a-11ef-a4fd-925b27b1cd31/search',
          method: 'POST',
        },
        {
          rel: 'queryables',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/catalogs/cat_0721004e-fe8a-11ef-a4fd-925b27b1cd31/queryables',
        },
        {
          rel: 'root',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/',
        },
        {
          rel: 'self',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/catalogs/cat_0721004e-fe8a-11ef-a4fd-925b27b1cd31',
        },
        {
          rel: 'child',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/catalogs/cat_0721004e-fe8a-11ef-a4fd-925b27b1cd31/collections/esacci-lst-s3a-day-monthly',
          title: 'EOCIS Monthly Land Surface Temperature (LST) Daytime Collection for Sentinel-3A',
        },
        {
          rel: 'child',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/catalogs/cat_0721004e-fe8a-11ef-a4fd-925b27b1cd31/collections/esacci-lst-s3a-night-monthly',
          title:
            'EOCIS Monthly Land Surface Temperature (LST) Nighttime Collection for Sentinel-3A',
        },
        {
          rel: 'child',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/catalogs/cat_0721004e-fe8a-11ef-a4fd-925b27b1cd31/collections/esacci-lst-s3b-day-monthly',
          title: 'EOCIS Monthly Land Surface Temperature (LST) Daytime Collection for Sentinel-3B',
        },
        {
          rel: 'child',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/catalogs/cat_0721004e-fe8a-11ef-a4fd-925b27b1cd31/collections/esacci-lst-s3b-night-monthly',
          title:
            'EOCIS Monthly Land Surface Temperature (LST) Nighttime Collection for Sentinel-3B',
        },
      ],
      title: 'EOCIS Monthly Land Surface Temperature (LST) Catalog for Sentinel-3',
      type: 'Catalog',
      keywords: [
        'Land Surface Temperature',
        'LST',
        'Sentinel-3',
        'SLSTR',
        'Monthly',
        'EOCIS',
        'Climate Change',
      ],
      license: 'ESA-CCI-Data-Policy-free-and-open-access',
      providers: [
        {
          name: 'University of Leicester',
          roles: ['producer', 'processor'],
          url: 'https://www.le.ac.uk/',
        },
        {
          name: 'European Space Agency',
          roles: ['producer', 'licensor'],
          url: 'https://www.esa.int/',
        },
      ],
      extent: {
        spatial: {
          bbox: [[-180, -90, 180, 90]],
        },
        temporal: {
          interval: [['2016-05-01T00:00:00Z', '2024-12-31T23:59:59Z']],
        },
      },
      stac_extensions: [],
      conformsTo: [
        'https://api.stacspec.org/v1.0.0/item-search',
        'http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/simple-query',
        'https://api.stacspec.org/v1.0.0/item-search#query',
        'https://api.stacspec.org/v1.0.0-rc.2/item-search#filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-text',
        'https://api.stacspec.org/v1.0.0/ogcapi-features',
        'https://api.stacspec.org/v1.0.0/collections',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson',
        'https://api.stacspec.org/v1.0.0-rc.1/ogcapi-features#free-text',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search#free-text',
        'https://api.stacspec.org/v1.0.0/core',
        'https://api.stacspec.org/v1.0.0-rc.1/item-search#free-text',
        'https://api.stacspec.org/v1.0.0/item-search#fields',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/basic-cql2',
        'https://api.stacspec.org/v1.0.0/item-search#sort',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/features-filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-json',
        'http://www.opengis.net/spec/cql2/1.0/conf/advanced-comparison-operators',
        'https://api.stacspec.org/v0.3.0/aggregation',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search',
      ],
    },
    {
      id: 'cat_331a1512-04db-11f0-a0a6-eadd75232b79',
      description:
        'This catalog contains level L2P land surface temperatures derived from Landsat 8 for London at 100m resolution.',
      stac_version: '1.0.0',
      links: [
        {
          rel: 'aggregate',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/catalogs/cat_331a1512-04db-11f0-a0a6-eadd75232b79/aggregate',
        },
        {
          rel: 'aggregations',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/catalogs/cat_331a1512-04db-11f0-a0a6-eadd75232b79/aggregations',
        },
        {
          rel: 'catalogs',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/catalogs/cat_331a1512-04db-11f0-a0a6-eadd75232b79/catalogs',
        },
        {
          rel: 'collections',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/catalogs/cat_331a1512-04db-11f0-a0a6-eadd75232b79/collections',
        },
        {
          rel: 'conformance',
          type: 'application/json',
          title: 'STAC/WFS3 conformance classes implemented by this server',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/conformance',
        },
        {
          rel: 'data',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/catalogs/cat_331a1512-04db-11f0-a0a6-eadd75232b79/collections',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/catalogs/cat_331a1512-04db-11f0-a0a6-eadd75232b79/search',
          method: 'GET',
        },
        {
          rel: 'parent',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/catalogs/cat_331a1512-04db-11f0-a0a6-eadd75232b79/search',
          method: 'POST',
        },
        {
          rel: 'queryables',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/catalogs/cat_331a1512-04db-11f0-a0a6-eadd75232b79/queryables',
        },
        {
          rel: 'root',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/',
        },
        {
          rel: 'self',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/catalogs/cat_331a1512-04db-11f0-a0a6-eadd75232b79',
        },
        {
          rel: 'child',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/catalogs/cat_331a1512-04db-11f0-a0a6-eadd75232b79/collections/esacci-lst-l2p-lndst8-london',
          title: 'ESACCI Land Surface Temperature (LST) Collection for London 100m resolution',
        },
      ],
      title: 'ESACCI Land Surface Temperature (LST) data for London 100m resolution',
      type: 'Catalog',
      keywords: ['Land Surface Temperature', 'LST', 'London', '100m', 'Climate Change'],
      license: 'ESA-CCI-Data-Policy-free-and-open-access',
      providers: [
        {
          name: 'University of Leicester',
          roles: ['producer', 'processor'],
          url: 'https://www.le.ac.uk/',
        },
      ],
      extent: {
        spatial: {
          bbox: [[-2.74900010873613, 50.6419999663789, 0.67799888396785, 52.7099993585329]],
        },
        temporal: {
          interval: [['2013-04-19T00:00:00Z', '2023-11-09T23:59:59Z']],
        },
      },
      stac_extensions: [],
      conformsTo: [
        'https://api.stacspec.org/v1.0.0/item-search',
        'http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/simple-query',
        'https://api.stacspec.org/v1.0.0/item-search#query',
        'https://api.stacspec.org/v1.0.0-rc.2/item-search#filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-text',
        'https://api.stacspec.org/v1.0.0/ogcapi-features',
        'https://api.stacspec.org/v1.0.0/collections',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson',
        'https://api.stacspec.org/v1.0.0-rc.1/ogcapi-features#free-text',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search#free-text',
        'https://api.stacspec.org/v1.0.0/core',
        'https://api.stacspec.org/v1.0.0-rc.1/item-search#free-text',
        'https://api.stacspec.org/v1.0.0/item-search#fields',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/basic-cql2',
        'https://api.stacspec.org/v1.0.0/item-search#sort',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/features-filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-json',
        'http://www.opengis.net/spec/cql2/1.0/conf/advanced-comparison-operators',
        'https://api.stacspec.org/v0.3.0/aggregation',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search',
      ],
    },
    {
      id: 'commercial-data',
      description: 'Catalog for isaacjenkinstpz commercial data',
      stac_version: '1.0.0',
      links: [
        {
          rel: 'aggregate',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/isaacjenkinstpz/catalogs/commercial-data/aggregate',
        },
        {
          rel: 'aggregations',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/isaacjenkinstpz/catalogs/commercial-data/aggregations',
        },
        {
          rel: 'catalogs',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/isaacjenkinstpz/catalogs/commercial-data/catalogs',
        },
        {
          rel: 'collections',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/isaacjenkinstpz/catalogs/commercial-data/collections',
        },
        {
          rel: 'conformance',
          type: 'application/json',
          title: 'STAC/WFS3 conformance classes implemented by this server',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/conformance',
        },
        {
          rel: 'data',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/isaacjenkinstpz/catalogs/commercial-data/collections',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/isaacjenkinstpz/catalogs/commercial-data/search',
          method: 'GET',
        },
        {
          rel: 'parent',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/isaacjenkinstpz',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/isaacjenkinstpz/catalogs/commercial-data/search',
          method: 'POST',
        },
        {
          rel: 'queryables',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/isaacjenkinstpz/catalogs/commercial-data/queryables',
        },
        {
          rel: 'root',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/',
        },
        {
          rel: 'self',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/isaacjenkinstpz/catalogs/commercial-data',
        },
      ],
      title: 'isaacjenkinstpz Commercial Data',
      type: 'Catalog',
      stac_extensions: [],
      conformsTo: [
        'https://api.stacspec.org/v1.0.0/item-search',
        'http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/simple-query',
        'https://api.stacspec.org/v1.0.0/item-search#query',
        'https://api.stacspec.org/v1.0.0-rc.2/item-search#filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-text',
        'https://api.stacspec.org/v1.0.0/ogcapi-features',
        'https://api.stacspec.org/v1.0.0/collections',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson',
        'https://api.stacspec.org/v1.0.0-rc.1/ogcapi-features#free-text',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search#free-text',
        'https://api.stacspec.org/v1.0.0/core',
        'https://api.stacspec.org/v1.0.0-rc.1/item-search#free-text',
        'https://api.stacspec.org/v1.0.0/item-search#fields',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/basic-cql2',
        'https://api.stacspec.org/v1.0.0/item-search#sort',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/features-filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-json',
        'http://www.opengis.net/spec/cql2/1.0/conf/advanced-comparison-operators',
        'https://api.stacspec.org/v0.3.0/aggregation',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search',
      ],
    },
    {
      id: 'commercial-data',
      description: 'Catalog for test-workspace commercial data',
      stac_version: '1.0.0',
      links: [
        {
          rel: 'aggregate',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/test-workspace/catalogs/commercial-data/aggregate',
        },
        {
          rel: 'aggregations',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/test-workspace/catalogs/commercial-data/aggregations',
        },
        {
          rel: 'catalogs',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/test-workspace/catalogs/commercial-data/catalogs',
        },
        {
          rel: 'collections',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/test-workspace/catalogs/commercial-data/collections',
        },
        {
          rel: 'conformance',
          type: 'application/json',
          title: 'STAC/WFS3 conformance classes implemented by this server',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/conformance',
        },
        {
          rel: 'data',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/test-workspace/catalogs/commercial-data/collections',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/test-workspace/catalogs/commercial-data/search',
          method: 'GET',
        },
        {
          rel: 'parent',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/test-workspace',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/test-workspace/catalogs/commercial-data/search',
          method: 'POST',
        },
        {
          rel: 'queryables',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/test-workspace/catalogs/commercial-data/queryables',
        },
        {
          rel: 'root',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/',
        },
        {
          rel: 'self',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/test-workspace/catalogs/commercial-data',
        },
      ],
      title: 'test-workspace Commercial Data',
      type: 'Catalog',
      stac_extensions: [],
      conformsTo: [
        'https://api.stacspec.org/v1.0.0/item-search',
        'http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/simple-query',
        'https://api.stacspec.org/v1.0.0/item-search#query',
        'https://api.stacspec.org/v1.0.0-rc.2/item-search#filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-text',
        'https://api.stacspec.org/v1.0.0/ogcapi-features',
        'https://api.stacspec.org/v1.0.0/collections',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson',
        'https://api.stacspec.org/v1.0.0-rc.1/ogcapi-features#free-text',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search#free-text',
        'https://api.stacspec.org/v1.0.0/core',
        'https://api.stacspec.org/v1.0.0-rc.1/item-search#free-text',
        'https://api.stacspec.org/v1.0.0/item-search#fields',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/basic-cql2',
        'https://api.stacspec.org/v1.0.0/item-search#sort',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/features-filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-json',
        'http://www.opengis.net/spec/cql2/1.0/conf/advanced-comparison-operators',
        'https://api.stacspec.org/v0.3.0/aggregation',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search',
      ],
    },
    {
      id: 'isaacjenkinstpz',
      description: 'Catalog for isaacjenkinstpz workspace',
      stac_version: '1.0.0',
      links: [
        {
          rel: 'aggregate',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/isaacjenkinstpz/aggregate',
        },
        {
          rel: 'aggregations',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/isaacjenkinstpz/aggregations',
        },
        {
          rel: 'catalogs',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/isaacjenkinstpz/catalogs',
        },
        {
          rel: 'collections',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/isaacjenkinstpz/collections',
        },
        {
          rel: 'conformance',
          type: 'application/json',
          title: 'STAC/WFS3 conformance classes implemented by this server',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/conformance',
        },
        {
          rel: 'data',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/isaacjenkinstpz/collections',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/isaacjenkinstpz/search',
          method: 'GET',
        },
        {
          rel: 'parent',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/isaacjenkinstpz/search',
          method: 'POST',
        },
        {
          rel: 'queryables',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/isaacjenkinstpz/queryables',
        },
        {
          rel: 'root',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/',
        },
        {
          rel: 'self',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/isaacjenkinstpz',
        },
        {
          rel: 'child',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/isaacjenkinstpz/catalogs/commercial-data',
          title: 'isaacjenkinstpz Commercial Data',
        },
        {
          rel: 'child',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/isaacjenkinstpz/catalogs/processing-results',
          title: 'isaacjenkinstpz Processing Results',
        },
        {
          rel: 'child',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/isaacjenkinstpz/catalogs/saved-data',
          title: 'isaacjenkinstpz Saved Data',
        },
      ],
      title: 'isaacjenkinstpz Workspace Catalog',
      type: 'Catalog',
      stac_extensions: [],
      conformsTo: [
        'https://api.stacspec.org/v1.0.0/item-search',
        'http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/simple-query',
        'https://api.stacspec.org/v1.0.0/item-search#query',
        'https://api.stacspec.org/v1.0.0-rc.2/item-search#filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-text',
        'https://api.stacspec.org/v1.0.0/ogcapi-features',
        'https://api.stacspec.org/v1.0.0/collections',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson',
        'https://api.stacspec.org/v1.0.0-rc.1/ogcapi-features#free-text',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search#free-text',
        'https://api.stacspec.org/v1.0.0/core',
        'https://api.stacspec.org/v1.0.0-rc.1/item-search#free-text',
        'https://api.stacspec.org/v1.0.0/item-search#fields',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/basic-cql2',
        'https://api.stacspec.org/v1.0.0/item-search#sort',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/features-filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-json',
        'http://www.opengis.net/spec/cql2/1.0/conf/advanced-comparison-operators',
        'https://api.stacspec.org/v0.3.0/aggregation',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search',
      ],
    },
    {
      id: 'minimalist-stac',
      description: 'Catalog for storing data generated by workflow minimalist-stac',
      stac_version: '1.0.0',
      links: [
        {
          rel: 'aggregate',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/aggregate',
        },
        {
          rel: 'aggregations',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/aggregations',
        },
        {
          rel: 'catalogs',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/catalogs',
        },
        {
          rel: 'collections',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/collections',
        },
        {
          rel: 'conformance',
          type: 'application/json',
          title: 'STAC/WFS3 conformance classes implemented by this server',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/conformance',
        },
        {
          rel: 'data',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/collections',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/search',
          method: 'GET',
        },
        {
          rel: 'parent',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/search',
          method: 'POST',
        },
        {
          rel: 'queryables',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/queryables',
        },
        {
          rel: 'root',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/',
        },
        {
          rel: 'self',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac',
        },
        {
          rel: 'child',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/catalogs/cat_0721004e-fe8a-11ef-a4fd-925b27b1cd31',
          title: 'EOCIS Monthly Land Surface Temperature (LST) Catalog for Sentinel-3',
        },
        {
          rel: 'child',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sparkgeouser/catalogs/processing-results/catalogs/minimalist-stac/catalogs/cat_331a1512-04db-11f0-a0a6-eadd75232b79',
          title: 'ESACCI Land Surface Temperature (LST) data for London 100m resolution',
        },
      ],
      title: 'minimalist-stac Outputs Catalog',
      type: 'Catalog',
      stac_extensions: [],
      conformsTo: [
        'https://api.stacspec.org/v1.0.0/item-search',
        'http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/simple-query',
        'https://api.stacspec.org/v1.0.0/item-search#query',
        'https://api.stacspec.org/v1.0.0-rc.2/item-search#filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-text',
        'https://api.stacspec.org/v1.0.0/ogcapi-features',
        'https://api.stacspec.org/v1.0.0/collections',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson',
        'https://api.stacspec.org/v1.0.0-rc.1/ogcapi-features#free-text',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search#free-text',
        'https://api.stacspec.org/v1.0.0/core',
        'https://api.stacspec.org/v1.0.0-rc.1/item-search#free-text',
        'https://api.stacspec.org/v1.0.0/item-search#fields',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/basic-cql2',
        'https://api.stacspec.org/v1.0.0/item-search#sort',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/features-filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-json',
        'http://www.opengis.net/spec/cql2/1.0/conf/advanced-comparison-operators',
        'https://api.stacspec.org/v0.3.0/aggregation',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search',
      ],
    },
    {
      id: 'npl',
      description: 'Catalog for npl workspace',
      stac_version: '1.0.0',
      links: [
        {
          rel: 'aggregate',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/aggregate',
        },
        {
          rel: 'aggregations',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/aggregations',
        },
        {
          rel: 'catalogs',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs',
        },
        {
          rel: 'collections',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/collections',
        },
        {
          rel: 'conformance',
          type: 'application/json',
          title: 'STAC/WFS3 conformance classes implemented by this server',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/conformance',
        },
        {
          rel: 'data',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/collections',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/search',
          method: 'GET',
        },
        {
          rel: 'parent',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/search',
          method: 'POST',
        },
        {
          rel: 'queryables',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/queryables',
        },
        {
          rel: 'root',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/',
        },
        {
          rel: 'self',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl',
        },
        {
          rel: 'child',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results',
          title: 'npl Processing Results',
        },
      ],
      title: 'npl Workspace Catalog',
      type: 'Catalog',
      stac_extensions: [],
      conformsTo: [
        'https://api.stacspec.org/v1.0.0/item-search',
        'http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/simple-query',
        'https://api.stacspec.org/v1.0.0/item-search#query',
        'https://api.stacspec.org/v1.0.0-rc.2/item-search#filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-text',
        'https://api.stacspec.org/v1.0.0/ogcapi-features',
        'https://api.stacspec.org/v1.0.0/collections',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson',
        'https://api.stacspec.org/v1.0.0-rc.1/ogcapi-features#free-text',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search#free-text',
        'https://api.stacspec.org/v1.0.0/core',
        'https://api.stacspec.org/v1.0.0-rc.1/item-search#free-text',
        'https://api.stacspec.org/v1.0.0/item-search#fields',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/basic-cql2',
        'https://api.stacspec.org/v1.0.0/item-search#sort',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/features-filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-json',
        'http://www.opengis.net/spec/cql2/1.0/conf/advanced-comparison-operators',
        'https://api.stacspec.org/v0.3.0/aggregation',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search',
      ],
    },
    {
      id: 'planet_psscene_qa',
      description: 'Root catalog for planet_psscene QA checks',
      stac_version: '1.0.0',
      links: [
        {
          rel: 'aggregate',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/catalogs/qa-workflow/catalogs/planet_psscene_qa/aggregate',
        },
        {
          rel: 'aggregations',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/catalogs/qa-workflow/catalogs/planet_psscene_qa/aggregations',
        },
        {
          rel: 'catalogs',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/catalogs/qa-workflow/catalogs/planet_psscene_qa/catalogs',
        },
        {
          rel: 'collections',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/catalogs/qa-workflow/catalogs/planet_psscene_qa/collections',
        },
        {
          rel: 'conformance',
          type: 'application/json',
          title: 'STAC/WFS3 conformance classes implemented by this server',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/conformance',
        },
        {
          rel: 'data',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/catalogs/qa-workflow/catalogs/planet_psscene_qa/collections',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/catalogs/qa-workflow/catalogs/planet_psscene_qa/search',
          method: 'GET',
        },
        {
          rel: 'parent',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/catalogs/qa-workflow',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/catalogs/qa-workflow/catalogs/planet_psscene_qa/search',
          method: 'POST',
        },
        {
          rel: 'queryables',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/catalogs/qa-workflow/catalogs/planet_psscene_qa/queryables',
        },
        {
          rel: 'root',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/',
        },
        {
          rel: 'self',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/catalogs/qa-workflow/catalogs/planet_psscene_qa',
        },
        {
          rel: 'child',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/catalogs/qa-workflow/catalogs/planet_psscene_qa/collections/qa_documentation',
          title: 'qa_documentation',
        },
        {
          rel: 'child',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/catalogs/qa-workflow/catalogs/planet_psscene_qa/collections/qa_radiometric',
          title: 'qa_radiometric',
        },
      ],
      type: 'Catalog',
      stac_extensions: [],
      title: '',
      conformsTo: [
        'https://api.stacspec.org/v1.0.0/item-search',
        'http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/simple-query',
        'https://api.stacspec.org/v1.0.0/item-search#query',
        'https://api.stacspec.org/v1.0.0-rc.2/item-search#filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-text',
        'https://api.stacspec.org/v1.0.0/ogcapi-features',
        'https://api.stacspec.org/v1.0.0/collections',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson',
        'https://api.stacspec.org/v1.0.0-rc.1/ogcapi-features#free-text',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search#free-text',
        'https://api.stacspec.org/v1.0.0/core',
        'https://api.stacspec.org/v1.0.0-rc.1/item-search#free-text',
        'https://api.stacspec.org/v1.0.0/item-search#fields',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/basic-cql2',
        'https://api.stacspec.org/v1.0.0/item-search#sort',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/features-filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-json',
        'http://www.opengis.net/spec/cql2/1.0/conf/advanced-comparison-operators',
        'https://api.stacspec.org/v0.3.0/aggregation',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search',
      ],
    },
    {
      id: 'processing-results',
      description: 'Catalog for npl processing results',
      stac_version: '1.0.0',
      links: [
        {
          rel: 'aggregate',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/aggregate',
        },
        {
          rel: 'aggregations',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/aggregations',
        },
        {
          rel: 'catalogs',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/catalogs',
        },
        {
          rel: 'collections',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/collections',
        },
        {
          rel: 'conformance',
          type: 'application/json',
          title: 'STAC/WFS3 conformance classes implemented by this server',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/conformance',
        },
        {
          rel: 'data',
          type: 'application/geo+json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/collections',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/search',
          method: 'GET',
        },
        {
          rel: 'parent',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl',
        },
        {
          rel: 'search',
          type: 'application/geo+json',
          title: 'STAC search',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/search',
          method: 'POST',
        },
        {
          rel: 'queryables',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/queryables',
        },
        {
          rel: 'root',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/',
        },
        {
          rel: 'self',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results',
        },
        {
          rel: 'child',
          type: 'application/json',
          href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/catalogs/qa-workflow',
          title: 'qa-workflow Outputs Catalog',
        },
      ],
      title: 'npl Processing Results',
      type: 'Catalog',
      stac_extensions: [],
      conformsTo: [
        'https://api.stacspec.org/v1.0.0/item-search',
        'http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/simple-query',
        'https://api.stacspec.org/v1.0.0/item-search#query',
        'https://api.stacspec.org/v1.0.0-rc.2/item-search#filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-text',
        'https://api.stacspec.org/v1.0.0/ogcapi-features',
        'https://api.stacspec.org/v1.0.0/collections',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson',
        'https://api.stacspec.org/v1.0.0-rc.1/ogcapi-features#free-text',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search#free-text',
        'https://api.stacspec.org/v1.0.0/core',
        'https://api.stacspec.org/v1.0.0-rc.1/item-search#free-text',
        'https://api.stacspec.org/v1.0.0/item-search#fields',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/basic-cql2',
        'https://api.stacspec.org/v1.0.0/item-search#sort',
        'http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/features-filter',
        'http://www.opengis.net/spec/cql2/1.0/conf/cql2-json',
        'http://www.opengis.net/spec/cql2/1.0/conf/advanced-comparison-operators',
        'https://api.stacspec.org/v0.3.0/aggregation',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core',
        'https://api.stacspec.org/v1.0.0-rc.1/collection-search',
      ],
    },
  ],
  links: [
    {
      rel: 'root',
      type: 'application/json',
      href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/',
    },
    {
      rel: 'parent',
      type: 'application/json',
      href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user',
    },
    {
      rel: 'self',
      type: 'application/json',
      href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs',
    },
    {
      rel: 'next',
      type: 'application/json',
      method: 'GET',
      href: 'https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs?token=processing-results',
    },
  ],
  numReturned: 10,
  numMatched: 19,
};
