import { Member } from './types';

export const membersPlaceholder: Member[] = [
  {
    id: 'a1b2c3d4-e5f6-7g8h-9i0j-k1l2m3n4o5p6',
    username: 'john_doe123',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
  },
  {
    id: 'p9o8i7u6-y5t4r3e2-w1q2z3x4c5v6b7',
    username: 'jane_smith',
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@example.com',
  },
  {
    id: 'k1j2h3g4-f5d6-s7a8-p9o0l1m2n3x4y5',
    username: 'random_user1',
    firstName: 'Random',
    lastName: 'User',
    email: 'random.user1@example.com',
  },
  {
    id: 'b2v3c4x5-z6a7-s8d9-e0f1g2h3j4k5l6',
    username: 'test_account',
    firstName: 'Test',
    lastName: 'Account',
    email: 'test.account@example.com',
  },
  {
    id: 'x4y5z6a7-b8c9-d0e1f2g3-h4j5k6l7m8n9',
    username: 'alice_wonder',
    firstName: 'Alice',
    lastName: 'Wonder',
    email: 'alice.wonder@example.com',
  },
  {
    id: 'f2g3h4j5-k6l7-m8n9o0p1-q2r3s4t5u6v7',
    username: 'bob_builder',
    firstName: 'Bob',
    lastName: 'Builder',
    email: 'bob.builder@example.com',
  },
  {
    id: 'o9p8q7r6-s5t4u3v2-w1x2y3z4a5b6c7d8',
    username: 'charlie_test',
    firstName: 'Charlie',
    lastName: 'Test',
    email: 'charlie.test@example.com',
  },
  {
    id: 'l7m8n9o0-p1q2r3s4-t5u6v7w8x9y0z1a2',
    username: 'delta_user',
    firstName: 'Delta',
    lastName: 'User',
    email: 'delta.user@example.com',
  },
  {
    id: 'y3z4x5w6-v7u8t9s0-r1q2p3o4n5m6l7k8',
    username: 'echo_test',
    firstName: 'Echo',
    lastName: 'Test',
    email: 'echo.test@example.com',
  },
  {
    id: 't6u7v8w9-x0y1z2a3-b4c5d6e7f8g9h0j1',
    username: 'foxtrot_user',
    firstName: 'Foxtrot',
    lastName: 'User',
    email: 'foxtrot.user@example.com',
  },
  {
    id: 'c5d6e7f8-g9h0j1k2-l3m4n5o6p7q8r9s0',
    username: 'golf_tester',
    firstName: 'Golf',
    lastName: 'Tester',
    email: 'golf.tester@example.com',
  },
  {
    id: 'm9n8o7p6-q5r4s3t2-u1v2w3x4y5z6a7b8',
    username: 'hotel_user',
    firstName: 'Hotel',
    lastName: 'User',
    email: 'hotel.user@example.com',
  },
  {
    id: 's4t5u6v7-w8x9y0z1-a2b3c4d5e6f7g8h9',
    username: 'india_test',
    firstName: 'India',
    lastName: 'Test',
    email: 'india.test@example.com',
  },
  {
    id: 'z1y2x3w4-v5u6t7s8-r9q0p1o2n3m4l5k6',
    username: 'juliet_user',
    firstName: 'Juliet',
    lastName: 'User',
    email: 'juliet.user@example.com',
  },
  {
    id: 'o8p9q0r1-s2t3u4v5-w6x7y8z9a0b1c2d3',
    username: 'kilo_tester',
    firstName: 'Kilo',
    lastName: 'Tester',
    email: 'kilo.tester@example.com',
  },
  {
    id: 'x2w3v4u5-t6s7r8q9-p0o1n2m3l4k5j6h7',
    username: 'lima_user',
    firstName: 'Lima',
    lastName: 'User',
    email: 'lima.user@example.com',
  },
];
