name: Test App
on:
  workflow_call:
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  test:
    name: Test Code
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup NodeJS version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Build app to prove it is in a sensible state
        run: |
          npm ci
          npm run test:ci
          npm run build

  security-scan:
    name: Call Security Scan
    uses: EO-DataHub/github-actions/.github/workflows/security.yaml@main
